# Server Configuration
server:
  port: 3001

# Application Configuration
spring:
  application:
    name: petstore-catalog-service
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  # WebFlux Configuration
  webflux:
    base-path: /
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/petstore_catalog}
    username: ${POSTGRES_USERNAME:your_username}
    password: ${POSTGRES_PASSWORD:your_password}
    pool:
      initial-size: ${R2DBC_POOL_INITIAL_SIZE:10}
      max-size: ${R2DBC_POOL_MAX_SIZE:20}
      max-idle-time: ${R2DBC_POOL_MAX_IDLE_TIME:30m}

# Logging Configuration
logging:
  level:
    "[com.coding2.the.max.petstore.catalog]": ${LOG_LEVEL:INFO}
    "[org.springframework.web.reactive]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Springdoc Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
